name: Deploy Zola with GitHub Pages

on:
  push:
    branches: ["main"]
env:
    ZOLA_VER: "v0.18.0"

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: get Zola binary
        run: |
          curl -LJO https://github.com/getzola/zola/releases/download/${ZOLA_VER}/zola-${ZOLA_VER}-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf zola-${ZOLA_VER}-x86_64-unknown-linux-gnu.tar.gz
          chmod +x zola
      
      - name: Build Zola site
        run: ./zola build

      # - name: Minify
      #   uses: kuznetsov17/minify@v1.3
      #   id: minify-site
      #   with:
      #     dir: 'public'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: 'public/'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
